[book]
authors = ["tercmd"]
language = "en"
multilingual = false
src = "src"
title = "HTMXify"
git_repository_url = "https://github.com/htmxify/docs"
git_repository_edit_url = "https://github.com/htmxify/docs"
cname = "https://htmxify.com"